### PR TITLE
Update my_axi_interface.v

### PR DESCRIPTION
**Pull request by Ellen7ions**
Is it wrong ?
“wready” or “awready” on line 181?

### CODE REVIEW

**Comment by SocialistDalao** [comment]
The AXI interface we have designed first waits for signal awready and then wready. line 181 means we are in state awready and are waiting for signal awready, not wready. The following lines work exactly same as we are talking now.

我们这个是先等信号awready再等wready，是状态awready就表示我们正在等待awready. 后面的状态处理同理。

if there are any further questions， feel free to ask.

**Comment by Ellen7ions** [comment]
I got u ! XD
But it was wrongly written as  "wready" in the master branch, I think u can merge it. :D

**Comment by SocialistDalao** [comment]
Well, but my branch seems nothing different from the correction from you.

**Comment by SocialistDalao** [comment]
oh sorry I know what's going wrong, thank you for your kind reminds

**Comment by SocialistDalao** [comment]
The final submission codes are different from codes under directory axi. This is a big warning, and i advise you to use latter one. Very sorry, this is an version management error.

**Comment by Ellen7ions** [comment]
Thx~

**Pull request merged**
